includeproject/urls.py
from django.contrib import admin
# 1) django.contrib에서 admin을 import해온다
from django.urls import path, include 
# 2) django.urls에서 path, include를 import해온다
# 2-1) path(): urlpatterns에 포함 할 요소를 반환한다.
# 2-2) include(): 다른앱안의  urls파일의 path들을 포함할 수 있게 해준다
from django.conf import settings
# 3) django.conf 에서 settings를 임포트한다
from django.conf.urls.static import static
# 4) django.conf.urls.static에서 static을 임포트한다
# 4-1) static(): 디버그 모드에서 파일을 제공하기위한 URL 패턴을 반환하는 도우미 함수이다
import staticapp.views
# 5) staticapp에 있는views 파일 임포트

"""
프로젝트 단위로 url을 관리하면 가독성이 떨어지고 유지보수가 힘들다.
따라서 장고 url이 제공하는 include함수를 사용하여 앱 별로 url 관리하는 게 좋다. 
"""
urlpatterns = [ 
# 6)Client로 부터 요청이 들어오면 그 요청을 보낼 경로를 정의한 리스트
    path('', staticapp.views.index, name="index"),
    # 7) 주소는 공란이고(주소의 첫페이지) staticapp.views.index 파일을 실행한다. 이때 name을 index로 지정하여 전체파일명 대신 쓸 수 있다.
    path('staticapp/', include('staticapp.urls')),
    # 8) 'staticapp.urls'를 포함하며 staticapp/ 주소뒤에 staticapp.urls가 붙는다
    path('mediaformapp/', include('mediaformapp.urls')),
    # 9) 'mediaformapp.urls'를 포함하며 mediaformapp/ 주소뒤에 mediaformapp.urls가 붙는다
    path('admin/', admin.site.urls),
    # 10) 주소창에 admin을 치면 admin을 연결한다. 
] 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
# 11) urlpatterns에 static파일에 대한 URL패턴을 반환한다
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
# 12) urlpatterns에 media파일에 대한 URL패턴을 반환한다

staticapp/urls.py
from django.urls import path
# 1) django.urls에서 path를 import해온다
# 1-1) path():  urlpatterns에 포함 할 요소를 반환한다.

from . import views
# 2) 현재 폴더의 views를 임포트한다

app_name = "staticapp"
# 3) 앱의 이름을 "staticapp"으로 설정(namespace)

urlpatterns = [
# 4) Client로 부터 요청이 들어오면 그 요청을 보낼 경로를 정의한 리스트
  path('', views.index, name="index"),
  # 5)  주소는 공란이고(주소의 첫페이지) views.index 파일을 실행한다. 이때 name을 index로 지정하여 전체파일명 대신 쓸 수 있다.
  path('blog/new', views.new, name="new"),
  # 6) 주소는 blog/new이고 views.new 파일을 실행한다. 이때 name을 new로 지정하여 전체파일명 대신 쓸 수 있다.
  path('blog/<int:blog_id>', views.detail, name="detail"),
  # 7) 주소는 blog/<int:blog_id>이고 views.detail 파일을 실행한다. 이때 name을 detail로 지정하여 전체파일명 대신 쓸 수 있다.

  path('blog/edit/<int:blog_id>', views.edit, name="edit"),
  # 8) 주소는 blog/edit/<int:blog_id>이고 views.edit 파일을 실행한다. 이때 name을 edit으로 지정하여 전체파일명 대신 쓸 수 있다.
  path('blog/delete/<int:blog_id>', views.delete, name="delete"),
  # 9)  주소는 blog/delete/<int:blog_id>이고 views.delete 파일을 실행한다. 이때 name을 delete로 지정하여 전체파일명 대신 쓸 수 있다.

]

staticapp/models.py
from django.db import models

class Blog(models.Model):
  title = models.CharField(max_length = 200, default = '제목 없음')
  # 1)models의 CharFiled 타입으로 title생성. 최대 길이는 200이고 default값음 '제목없음'
  body = models.TextField()
  created_at = models.DateTimeField(auto_now_add = True) 
  def __str__(self):
    return self.title
  class Meta:
    ordering = ['-created_at']

staticapp/views.py
### mediaformapp에 있는 view에 주석을 먼저 작성해보고 작성해주세요.

from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
# 1).models 에서 Blog 테이블을 임포트해온다
from datetime import datetime
from django.utils import timezone

def index(request):
# 2)index함수가 요청을받고 
  blog_list = Blog.objects.all()
  # 3)Blog.objects.all로 모든 객체를 blog_list에 담는다
  return render(request,'index.html', {'blogs':blog_list})
  # 4)blog_list를 blogs 딕셔너리에 저장하여 index.html와 결합한 뒤 응답을 보낸다

def new (request):
# 5)new함수가 요청을받고 
  if request.method == 'POST': 
  # 6)만약 요청받은 method가 POST라면
    blog = Blog()
    # 7)models에 정의된 클래스의 객체를 하나 생성한다
    blog.title = request.POST['title']
    # 8)생성한 blog객체의 title에 요청들어온(새로 작성한) title을 담는다
    blog.body = request.POST['body']
    # 9)생성한 blog객체의 body에 요청들어온(새로 작성한) body를 담는다
    blog.created_at = timezone.datetime.now()
    # 10)생성한 created_at에 timezone.datetime.now()로 작성일을 담는다
    blog.save()
    # 11)새로만든 객체를 저장해준다
   # return redirect('index')
    return redirect('/')
    # 12)첫 공백주소로 redirect해준다
  else:                       
  # 13)요청받은 method가 GET이라면(맨 처음 new가 실행될 때 페이지를 생성함)
    return render(request, 'static_new.html')
    # 14)'static_new.html'를 띄운다

def detail(request, blog_id):
# 15)detail이 요청을받고 id값을 받음
  blog = get_object_or_404(Blog, pk = blog_id)
  # 16)첫번째 매개변수로 우리가 가져와야할 테이블,두번째 매개변수는 pk (Primary Key 즉, 데이터베이스에서의 id)를 
  #가져오는데 못가져올 경우 예외를 처리해준다
  #가져온 객체를 blog에 담는다
  return render(request, 'static_detail.html', {'blog':blog})
  # 17)가져온 객체를 딕셔너리에 담아 'static_detail.html'와 결합시켜 응답을 보낸다

def edit(request, blog_id):
  # 18)edit가 요청 받고 id값을 받음
  blog = get_object_or_404(Blog, pk = blog_id)
  # 19)get_object_or_404로 해당하는 id에 맞는 객체를 blog에 담는다
  if request.method == 'POST':
    blog.title = request.POST['title']
    blog.body = request.POST['body']
    blog.created_at = timezone.datetime.now()
    blog.save()
    return redirect('/staticapp/blog/'+str(blog_id))
    # 20)/staticapp/blog/+str(blog_id)로 redirect보낸다.
    # 기능을 작동후 원래 페이지로 돌아가야하기때문에 redirect
  else:
    return render(request, 'static_edit.html', {'editblog':blog})
    # 21)가져온 객체를 editblog딕셔너리에 담아 'static_edit.html'와 결합시켜 응답을 보낸다

def delete(request, blog_id):
# 22)delete가 요청 받고 id값을 받음
  blog = Blog.objects.get(pk = blog_id)
  # 23)pk가 blog_id인 객체를 blog로 받아온다
  blog.delete() 
  # 24)받아온 blog를 삭제함
  return redirect('/')
  # 25)홈으로 redirect보낸다

staticapp/templates/index.html
{% load static %}
<!-- 1. static 파일들을 로드(상단에 명시해야함) -->
<a href="{% url 'staticapp:new' %}">New</a><br>
<!-- 2. 템플릿 태그로 staticapp의 new에 a태그를 걸었다-->
<img src="{% static 'image1.jpeg' %}" alt="image1">
<!-- 3.  static파일을 가져옴 -->
{% for blog in blogs %}
<!-- 4. views.py에서 넘겨받은 blogs 객체 목록을 하나씩 처리할 수 있도록함-->
  {{blog.title}}<br>
  <!-- 5. blog.title 속성 -->
  {{blog.body}}<br>
  {{blog.created_at}}<br>
  <a href="{% url 'staticapp:detail' blog.id %}">detail</a><br>
  <!-- 6. detail를 a태그로 연결한다 이때 detail에서 필요한 blog의 id도 같이보낸다(필요한 blog의 id값으로)) -->
{% endfor %}

staticapp/templates/static_detail.html
{{blog.title}}
{{blog.body}}
{{blog.date}}
<a href="{% url 'staticapp:edit' blog.id %}">edit</a>
<a href="{% url 'staticapp:delete' blog.id %}">delete</a>
<a href="{% url 'staticapp:index' %}">home</a>

staticapp/templates/static_edit.html
<form method="POST">
  {% csrf_token%}
  Title: <input type="text" name="title" value="{{editblog.title}}"><br>
<!-- 1.views.py를 통해 받아온 editblog의 title값을 value로 받음-->
  Body:<br><textarea rows="5" name="body">{{editblog.body}}</textarea><br>
  <input type="submit" value="수정">
</form>

staticapp/templates/static_new.html
<!-- forms.py를 사용하지 않은 경우 -->
<form method="POST" action="{% url 'staticapp:new' %}">
  <!-- 1. <form> 태그  method속성으로 전송방식을 택하고 (post 방식-url에 데이터 정보 미표시)
     action 속성은 데이터를 보낼 곳의 url을 명시 
  제출 버튼이 눌리면 staticapp앱의 new 이름을 가진 url 호출
  new 이름을 가진 url은 view의 new 함수를 호출
  -->
    {% csrf_token%}
    <!-- 2) POST로 format요청이 보내질 때 csrf-token(임의의 랜덤한 값)이 같이 보내지게 되면 
    csrf-token값을 통해서csrf공격이 아니라는 걸 인식하여 공격에 대한 방지를 함 -->
    Title: <input type="text" name="title"><br>
    Body:<br><textarea rows="5" name="body"></textarea><br>
    <input type="submit" value="제출">
  </form>